# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_cache: Rscript -e 'remotes::install_version("pkgdown", "1.4.1")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

